media: nexell: set `pix.sizeimage' for v4l2 app
This reverts commit 161657501e16 to fix GStreamer
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
  Video device did not suggest any buffer size.

Change-Id: I2e1ba362c3c2cecd72aed071c04954c3d74c8346
Signed-off-by: hmz007 <hmz007@gmail.com>